title: Debasmita Das
url: "https://debasmita-econ.github.io/"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#tracking_id: 

sass:
    style: compressed
    sass_dir: _sass
